services:
  - type: web
    name: flavorverse
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/flavorverse-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: flavorverse-db
          property: connectionString
    healthCheckPath: /actuator/health

databases:
  - name: flavorverse-db
    databaseName: flavorverse
    user: flavorverse_user
